### PR TITLE
Create linear-search.java

### PR DESCRIPTION
**Pull request by nitishmalang**
bro please merge my pr

### CODE REVIEW

**Comment by Dnyaneshvn** [comment]
yes, I will merge this pr, but create a linear search folder and add this file there.
if you have any queries feel free to ask me :)

**Comment by Dnyaneshvn** [comment]
Thanks @nitishmalang !! Make sure to give the repository a star 🌟

**Comment by nitishmalang** [comment]
bro I already starred & forked when you will merge it will become seperate folder linear search

**Comment by nitishmalang** [comment]
thanks for merging I will share it with my friends

**Comment by Dnyaneshvn** [comment]
yes, sure!

**Comment by Dnyaneshvn** [comment]
bro see in main branch your linear search code not in separate folder..
make another pr ..

how to add new folder:
step1: fork this repo (you already forked so, no need to fork)
step2: select your branch
and after 
step3: choose option in row add code
click on it..
you have to write there name of the code..
we have make folder along with code..
that's why 
write there,
DSA-in-JAVA/  these is already present there you need to add **filename/codename**

**Comment by nitishmalang** [comment]
> 

okay bro doing it

**Comment by nitishmalang** [comment]
> 

okay bro doing it

**Pull request merged**
