### PR TITLE
TwoDArray.java

### PR DESCRIPTION
**Pull request by aryan9042**
hacktoberfest-accepted

### CODE REVIEW

**Review by Dnyaneshvn — CHANGES_REQUESTED** [review]
add this file in array folder

**Comment by Dnyaneshvn** [comment]
if you have any queries regarding this then feel free to ask me

**Comment by aryan9042** [comment]
can you please gudie me how to do that

**Comment by Dnyaneshvn** [comment]
Yes I will

**Comment by aryan9042** [comment]
Then please tell me how i add this file in array folder

**Comment by Dnyaneshvn** [comment]
go to where you added your code and do following steps:
name is currently like this: Coding-Delight-01/DSA-in-JAVA/ TwoDArray.java 
but you need to add here: Coding-Delight-01/DSA-in-JAVA/ arrays/TwoDArray.java 

(you need to just add before your filename add : /arrays)
then your file is moved to arrays folder.

**Comment by Dnyaneshvn** [comment]
Hey, Aryan make another PR and do this properly (for practice purpose)
For this PR I will merge it and I will shift this code to the arrays folder.

**Review by Dnyaneshvn — APPROVED** [review]

**Comment by aryan9042** [comment]
Okay I will try to do it

**Pull request merged**
